name: Deploy to GitHub Pages 
 
on: 
  push: 
    branches: [ "main" ] 
 
permissions: 
  contents: read 
  pages: write 
  id-token: write 
 
jobs: 
  deploy: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout repository 
        uses: actions/checkout@v4 
 
      - name: Upload static files 
        uses: actions/upload-pages-artifact@v4 
        with: 
          path: ./ 
 
      - name: Deploy to GitHub Pages 
        uses: actions/deploy-pages@v4 
        with: 
          artifact_name: static-site 
